const BASES = {
    PROFILE: '/profile',
    PROJECTS: '/projects',
    SESSION: '/session',
};

const ROUTES_PARTS = {
    ACTIVATE: '/activate',
    RESEND_CONFIRMATION: '/resend-confirmation',
    PASSWORD_RESET: '/password-reset',
    PASSWORD_UPDATE: '/password-update',
};

export const ROUTES = {
    PROJECTS: {
        BASE: BASES.PROJECTS,
        GET_ALL: '',
        ADD: '',
    },
    PROFILE: {
        BASE: BASES.PROFILE,
        ACTIVATE: ROUTES_PARTS.ACTIVATE,
        RESEND_CONFIRMATION: ROUTES_PARTS.RESEND_CONFIRMATION,
        PASSWORD_RESET: ROUTES_PARTS.PASSWORD_RESET,
        PASSWORD_UPDATE: ROUTES_PARTS.PASSWORD_UPDATE,
    },
    SESSION: {
        BASE: BASES.SESSION,
        LOG_IN: '',
    },
};

export const ALLOWED_ROUTES = [
    `${ROUTES.PROFILE.BASE}`,
    `${ROUTES.PROFILE.BASE}${ROUTES.PROFILE.ACTIVATE}`,
    `${ROUTES.PROFILE.BASE}${ROUTES.PROFILE.RESEND_CONFIRMATION}`,
    `${ROUTES.PROFILE.BASE}${ROUTES.PROFILE.PASSWORD_RESET}`,
    `${ROUTES.PROFILE.BASE}${ROUTES.PROFILE.PASSWORD_UPDATE}`,

    `${ROUTES.SESSION.BASE}`,
];
